Repository drogue-iot/drogue-cloud, pull requests merged in 2021-11, with the labels that each got.

#155 fix: Fix the operator queue loosing events
  Cargo.lock
  operator-common/Cargo.toml
  operator-common/src/controller/base/mod.rs
  operator-common/src/controller/base/queue.rs
  operator-common/src/controller/reconciler/error.rs
  operator-common/src/lib.rs
  operator-common/tests/basic.rs
  operator-common/tests/common.rs
  registry-events/Cargo.toml
  topic-operator/Cargo.toml
  ttn-operator/Cargo.toml
Labels: bug

#153 feat: add MQTT integration to drogue-cloud-server
  Cargo.lock
  command-endpoint/src/lib.rs
  endpoint-common/src/sender/mod.rs
  mqtt-integration/src/lib.rs
  server/Cargo.toml
  server/src/main.rs
  service-common/src/defaults.rs
Labels: enhancement

#163 enforce rules on app and devices names
  Cargo.lock
  device-management-service/Cargo.toml
  device-management-service/src/endpoints/apps.rs
  device-management-service/src/endpoints/devices.rs
  device-management-service/tests/apps.rs
  device-management-service/tests/devices.rs
Labels: bug

#174 Add a drg card in overview
  console-frontend/src/pages/overview.rs
Labels: component/console

#175 build: split off console-frontend
  Cargo.lock
  Cargo.toml
  Makefile
  console-frontend/Cargo.lock
  console-frontend/Cargo.toml
Labels: component/console
